// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xikxyrbtdqqieybeouvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpa3h5cmJ0ZHFxaWV5YmVvdXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTIxOTQsImV4cCI6MjA3MTA4ODE5NH0.C6h6P3gnQxAHcgyWYtwvDwduUJ9RawhkLu9w-27iRjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});